language: node_js
node_js: "lts/*"
cache:
  directories:
    - "node_modules"

install:
  - npm install

addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token:
      secure: $SONAR_TOKEN

script:
  - npm run test
  - npm run build

stages:
  - name: after_success
    if: branch != master

after_success:
  - npm run coverage
  - sonar-scanner

before_deploy:
  - npm run coverage
  - npx standard-version
  - git remote add origin-pages https://$GH_TOKEN@github.com/AlexeyPopovUA/advanced-logger.git > /dev/null 2>&1
  - git push --follow-tags origin master
  - sonar-scanner

deploy:
  provider: npm
  email: $DEPLOY_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master