language: node_js
node_js: "lts/*"
cache:
  directories:
    - "node_modules"

install:
  - npm install

addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token:
      secure: $SONAR_TOKEN
    branches:
      ^((?!@).)*$

script:
  - npm run coverage
  - npm run build
  - sonar-scanner

deploy:
  skip_cleanup: true
  provider: npm
  email: $DEPLOY_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true